### ISSUE TITLE
Small things

### ISSUE THREAD

**Issue by davelab6** [PostStudio/Benne#9]
About the release

- [x] Release ZIPs must contain the OFL.txt license file, and the README
- [x] Release ZIPs can omit source files, if the README points to where to get them from
- [x] The release ZIP contains web font format files, but there is no source script to generate them in the source repo

About the repo

- [x] the Renders and Autohint dirs seem similar, maybe move Renders into a date subdir of Autohint
- [x] the LICENSE file isn't quite correct, I'll make a PR to adjust it to match what is in the font. 

About the TTF

- [x] The postScriptName is `Benne-Text` but should be `Benne-Regular`
- [x] fullName should was `Benne-Text`, should be `Benne Text`
- [x] fsType should be 0 ('not set' or 'installable') not 8 ('editable'). (This is a UI bug in Glyphs I have reported)
- [x] Copyright notice should match the OFL.txt and not have non-ascii characters. 

You could list them all on one line like this:

    Copyright 2015 by John-Daniel Harrington. All rights reserved. Copyright 2015 by Georg Duffner. All rights reserved. Copyright 2015 by Indian Type Foundry. All rights reserved.

But I think its better to have like [this example](https://github.com/NDISCOVER/Arima-Font/blob/master/OFL.txt#L1)

    Copyright 2015 The Benne Project Authors (info@poststudio.net)

And then have an [AUTHORS.txt](https://github.com/NDISCOVER/Arima-Font/blob/master/AUTHORS.txt) file and an [CONTRIBUTORS.txt](https://github.com/NDISCOVER/Arima-Font/blob/master/CONTRIBUTORS.txt) file keeping the list.

**Comment by misemefein** [comment]
Edited accordingly

**Comment by davelab6** [comment]
Here's how to set the fsType to 0:

<img width="685" alt="screen shot 2016-03-02 at 01 53 22" src="https://cloud.githubusercontent.com/assets/261579/13636933/7fd56a6e-e5d2-11e5-9f58-90772942df69.png">

**Comment by misemefein** [comment]
Ah, thanks for showing that
